version: '3.8'
services:
  php-apache-environment:
    container_name: acl-php
    build:
      context: ./src/scripts/php
      dockerfile: Dockerfile
    volumes:
      - ./src/:/var/www/html/
    ports:
      - 8000:80
