version: '3.8'
services:
  php-apache-environment:
    container_name: acl-php
    build:
      context: ./src/scripts/php
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./src/:/var/www/html/
    ports:
      - 8000:80

  db:
    container_name: db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Capyz0ra@1920
      MYSQL_DATABASE: acl
      MYSQL_USER: user
      MYSQL_PASSWORD: Capyz0ra@1920
    ports:
      - "9906:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
